version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wp_restau_abou_sohaib_db
    restart: on-failure
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: .
    container_name: wp_restau_abou_sohaib_app
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./wp-content:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_restau_abou_sohaib_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: on-failure
    env_file:
      - .env

volumes:
  db_data: {}
