version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build: .
    container_name: wp_app
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    env_file:
      - .env

volumes:
  db_data: {}
